### ISSUE TITLE
yank or delete operators + highlight_on_key = true 

### ISSUE THREAD

**Issue by ElPiloto** [jinh0/eyeliner.nvim#12]
Hello,  This is a pretty cool plugin! I'm wondering if I have something misconfigured but I can't seem to get the auto-highlight to show when the `f/F/t/T` commands are preceded by a yank or delete operator.  For example, typing `dt` or `yt` never turns on the highlights.   Thanks!

**Comment by jinh0** [comment]
Should be fixed with the latest commit 38e090adb5f56d6c06000a8bfdf3098554d7b784 . Thanks for the feature request, I totally forgot about that!
