### ISSUE TITLE
Vim macros using `f` don't work correctly

### ISSUE THREAD

**Issue by LostNeophyte** [jinh0/eyeliner.nvim#17]
easy to reproduce: 
1. copy this line `| A | B | C|`
2. record this macro `0lvf|x$p` (put the `A` column at the end)
3. execure the macro on the line

Expected behavior:  execute `0lvf|x$p` (that's what happens in nvim)
Actual: executes `0lvx$pf|` (`f|` gets executed at the end)

**Comment by williamhCode** [comment]
same for me

**Comment by jinh0** [comment]
Thanks for the pull request @LostNeophyte !
