### ISSUE TITLE
highlight_on_key = true has no effect on default AstroNvim config

### ISSUE THREAD

**Issue by davis-jordan** [jinh0/eyeliner.nvim#24]
Hi, I have recently based my nvim config off of this project: https://github.com/AstroNvim/AstroNvim

With a fresh pull of AstroNvim, the highlight_on_key option has no effect. By this, I mean that even though I have set Eyeliner only to show the highlights when pressing f,F,t,T, the highlights are showing up all the time.

Here is the user-defined plugins block of AstroNvim that I have:
<img width="950" alt="image" src="https://user-images.githubusercontent.com/32600362/215243006-5383fc80-61a7-4285-8b4c-0e0128f7fc5a.png">

Despite this, every file that I open has highlights on every line by default, like this: (f was not pressed here) 
<img width="687" alt="image" src="https://user-images.githubusercontent.com/32600362/215243035-4bb5c19f-7555-42e6-82c7-f9bea3f69789.png">

I have also tried adding this autocmd in the Eyeliner Documentation:
```
vim.api.nvim_create_autocmd('ColorScheme', {
  pattern = '*',
  callback = function()
    vim.api.nvim_set_hl(0, 'EyelinerPrimary', { bold = true, underline = true })
  end,
})
```

Any ideas on how to rectify this would be very appreciated!

**Comment by jinh0** [comment]
Hi @davis-jordan , were you able to solve the issue? What was the solution?

**Comment by Xiione** [comment]
Would like to know how this was solved as well. I'm experiencing the same issue right now after switching to lazy.nvim as my plugin manager, from packer.nvim.
