### ISSUE TITLE
highlight_on_key = true breaks macros

### ISSUE THREAD

**Issue by mercxry** [jinh0/eyeliner.nvim#25]
Hello 👋 
Thanks for the plugin, it makes jumping to a character way faster visually 🙏 

However I noticed that enabling `highlight_on_key` breaks macros which include the use of the `f` key, an example video below:

https://user-images.githubusercontent.com/39272153/215800890-d3f05443-060e-473f-b472-f08509c67d94.mp4

I tried disabling the `highlight_on_key` option and the same macro starts working correctly again.

I usually offer to make a PR, but to be honest here I'm not familiar with neovim plugin development nor where to start to fix this problem 😅 
But let me know if there is anything else I can help with 😄

**Comment by mercxry** [comment]
Additional demo of enabling and disabling eyeliner to show how it's supposed to look like as well
https://user-images.githubusercontent.com/39272153/215804662-4955561e-4eac-4f67-95fe-9801929f259e.mp4

**Comment by jinh0** [comment]
Hey @mercxry , this has been fixed in 6a9d0ad714f11cab1691e54e936eaa9881cad277 ! Thanks for the issue!

Related: https://github.com/gukz/ftFT.nvim/issues/7
