### ISSUE TITLE
Confused about the rule of highlight

### ISSUE THREAD

**Issue by Weissle** [jinh0/eyeliner.nvim#28]
![image](https://user-images.githubusercontent.com/29982556/219276587-a64675f7-ebe0-4103-8f6b-fa7d96119157.png)
According to the highlight, I can jump to `i M l c t` immediately and jump to `n` (in `nil`) by pressing `n;` ( jump to the first `n` (in `_config` and repeat).
However, why the char `s` in `M[lsp` is not highlighted? why the first `n` ( in `_config`) is not highlighted?
Could you please tell us more details about the highlighted rule?

**Comment by jinh0** [comment]
Hi! To clarify, yes, you can jump to s and n, but eyeliner only highlights one character per word, prioritizing the leftmost character.
