### ISSUE TITLE
Error in commit 4cf1aaff79a2754d2cb1eac6a67c3987ce2e484

### ISSUE THREAD

**Issue by CRAG666** [jinh0/eyeliner.nvim#3]
![screen-1657646203](https://user-images.githubusercontent.com/34254373/178553515-30294baa-1364-4305-864d-40ddeba2c776.png)

**Comment by CRAG666** [comment]
I just upgraded to the last commit and skips the error shown in the image

**Comment by jinh0** [comment]
Sorry about this, I think it has to do with when you don't run `require'eyeliner'.setup{}`. I was just able to replicate this error. I'm working on a fix right now!
