### ISSUE TITLE
Error when using with `nvim-bqf` and `set splitkeep=topline`

### ISSUE THREAD

**Issue by joshuali925** [jinh0/eyeliner.nvim#35]
Hi, i've been trying out this plugin to see if it's better than quick-scope, but i kept getting this error.

Steps:

1. install eyeliner, [nvim-bqf](https://github.com/kevinhwang91/nvim-bqf), lsp
2. `set splitkeep=topline`
3. open `lua/eyeliner/liner.lua`, go to line 102 (cursor at `get_locations`)
4. press `zb`, run `:lua vim.lsp.buf.references()`
5. see error:

```
Error executing vim.schedule lua callback: ...cal/lib/nvim/share/nvim/runtime/lua/vim/lsp/handlers.lua:23
9: CursorMoved Autocommands for "*": Vim(append):Error executing lua callback: ...cal/share/nvim/lazy/eye
liner.nvim/lua/eyeliner/liner.lua:59: table index is nil
stack traceback:
        ...cal/share/nvim/lazy/eyeliner.nvim/lua/eyeliner/liner.lua:59: in function 'get_tokens'
        ...cal/share/nvim/lazy/eyeliner.nvim/lua/eyeliner/liner.lua:120: in function 'get_locations'
        ...share/nvim/lazy/eyeliner.nvim/lua/eyeliner/always-on.lua:17: in function <...share/nvim/lazy/e
yeliner.nvim/lua/eyeliner/always-on.lua:12>
        [C]: in function 'nvim_command'
        ...cal/lib/nvim/share/nvim/runtime/lua/vim/lsp/handlers.lua:239: in function 'handler'
        .../.local/lib/nvim/share/nvim/runtime/lua/vim/lsp.lua:1394: in function ''
        vim/_editor.lua: in function <vim/_editor.lua:0>
stack traceback:
        [C]: in function 'nvim_command'
        ...cal/lib/nvim/share/nvim/runtime/lua/vim/lsp/handlers.lua:239: in function 'handler'
        .../.local/lib/nvim/share/nvim/runtime/lua/vim/lsp.lua:1394: in function ''
        vim/_editor.lua: in function <vim/_editor.lua:0>
```

Adding a simple null check on https://github.com/jinh0/eyeliner.nvim/blob/fa3a0986cb072fe2ab29ef79e022514d2533f0db/lua/eyeliner/liner.lua#L56
 would prevent the error, but i didn't fully understand the code or why it happens. Let me know if i should send the minimal effort PR, or i appreciate it if you could take a look. Thanks.

**Comment by jinh0** [comment]
Hey @joshuali925  sorry for taking so long to respond. It's peculiar because I haven't actually been able to replicate your issue, but I have added the null check in the latest commit. Hope that fixes this!

**Comment by joshuali925** [comment]
i can confirm the error no longer happens, thanks!
