### ISSUE TITLE
Need to set `clear=true` for the augroup to prevent lagging after changing between colorschemes

### ISSUE THREAD

**Issue by nyngwang** [jinh0/eyeliner.nvim#36]
As title. Otherwise Neovim will get frozen after changing between colorschemes because of the title.

**Comment by jinh0** [comment]
Hey @nyngwang  I added the `clear` option in the latest commit, hope that fixes the lag! I am a little curious since the documentation does say that the `clear` option is enabled by default.

Let me know if you are still experiencing lag!

**Comment by nyngwang** [comment]
I still encountered the same frozen issue after trying 0b21a86.

**Comment by Yuhf7** [comment]
> I am a little curious since the documentation does say that the `clear` option is enabled by default.

To my knowledge, `clear` is enabled by default; however, that only applies to *creating* the augroup.
If you re-create the same autocommand without first clearing the augroup it won't remove previous autocommands.
https://github.com/jinh0/eyeliner.nvim/blob/a6c05ed7f2a59640bd18ff0702694deda483a08e/fnl/eyeliner/shared.fnl#L18-L19

Here you'd have to call `vim.api.nvim_create_augroup("Eyeliner", {})` before assigning "Eyeliner" to `group`.

**Comment by nyngwang** [comment]
@Yuhf7 While I don't have time to confirm it, it sounds promising! Thanks for your help!

**Comment by jinh0** [comment]
I merged your pull request @Yuhf7 ! @nyngwang Let me know if it's fixed!

**Comment by nyngwang** [comment]
@jinh0 It works :) Now I can install it back! Thank you!
