### ISSUE TITLE
feature: `max_line_length` option

### ISSUE THREAD

**Issue by llllvvuu** [jinh0/eyeliner.nvim#41]
Certain compiled JavaScript files can be a single line with hundreds of KB of text. In this case it would be nice to have eyeliner not trigger for that line (or only search up to the `max_line_length`-th character).

Here's my workaround currently, but it's not quite the same condition:
```lua
return {
  {
    'jinh0/eyeliner.nvim',
    config = function()
      require'eyeliner'.setup({})
      vim.api.nvim_create_autocmd(
        "BufReadPre", {
          pattern = "*",
          command = 'if getfsize(expand("%")) > 100000 | execute "EyelinerDisable" | endif'
        }
      )
    end
  }
}
```

**Comment by jinh0** [comment]
Sorry for the year-long inactivity on this repository, but if you're still interested, I have added this feature in the latest commit https://github.com/jinh0/eyeliner.nvim/commit/22a5c94f14eb286b25aed56e9c1ae90e53d2d520 of eyeliner!

You can enable this feature with:
```lua
  require'eyeliner'.setup({
    max_length = 80
  })
```

eyeliner will only look and highlight at most 80 characters from your current cursor.

Thanks for the suggestion!
