### ISSUE TITLE
Bug: `lazy.nvim Invalid 'group': '--Deleted--'`

### ISSUE THREAD

**Issue by grig-iv** [jinh0/eyeliner.nvim#44]
### Describe the bug
![image](https://github.com/jinh0/eyeliner.nvim/assets/77640875/fcd2f1f3-721a-4a7f-9e59-b7879de13a97)

I'm getting this error when `event = "BufReadPost/BufRead"`, but not for `BufReadPre`

### Minimal `init.lua` configuration
```lua
local lazypath = vim.fn.stdpath('data') .. '/lazy/lazy.nvim'
if not vim.loop.fs_stat(lazypath) then
    vim.fn.system({
        'git',
        'clone',
        '--filter=blob:none',
        'https://github.com/folke/lazy.nvim.git',
        '--branch=stable',
        lazypath,
    })
end
vim.opt.rtp:prepend(lazypath)

require('lazy').setup(
    {
        {
            'jinh0/eyeliner.nvim',
            event = 'BufReadPost',
	    opts = { },
        }
    }
)
```

### Versions
neovim: `v0.9.1`
lazy-lock:
```
"eyeliner.nvim": { "branch": "main", "commit": "c540d58bf52aa979d4cca639c60387ae0c0ccf88" },
"lazy.nvim": { "branch": "main", "commit": "4c75c8eeb957a99aa44ce8e526c04340ab358c5e" }
```

**Comment by shellheim** [comment]
It also triggers on `event = 'InsertEnter'`. I went insane trying to find the problem.

### Versions 
neovim `v0.9.5`
lazy-lock : 
```
  "eyeliner.nvim": { "branch": "main", "commit": "c540d58bf52aa979d4cca639c60387ae0c0ccf88" },
  "lazy.nvim": { "branch": "main", "commit": "28126922c9b54e35a192ac415788f202c3944c9f" },
```

**Comment by jinh0** [comment]
Seems to not be a problem anymore with the latest versions of lazy.nvim and eyeliner.nvim. Closing this issue unless people encounter this again. I believe this was an issue with how events are handled in lazy.nvim.
