### ISSUE TITLE
change `f/F` to another key

### ISSUE THREAD

**Issue by daUnknownCoder** [jinh0/eyeliner.nvim#48]

**Comment by jinh0** [comment]
Could you elaborate a little? Is it that you have f/F functionality mapped to different keys? In that case, yes, currently, eyeliner.nvim will not work as intended when using the on-key mode. Can you share how you have mapped f/F functionality to different keys? Depending on how you've mapped them, the way I can implement this feature differs.

**Comment by daUnknownCoder** [comment]
Like F/f is remapped to folke's flash.nvim (treesitter search) so if I can remap this to an alt key which is unused that will b great
Bonus : is ur name `Jinho Yoon` or is it a solo leveling reference?

**Comment by jinh0** [comment]
Hi @daUnknownCoder , I've added the config option `default_keymaps` so that you can disable eyeliner.nvim from automatically adding f/F/t/T keymaps. eyeliner.nvim's internal highlight method is also now exposed as `require("eyeliner").highlight({ forward = true })` so you can use it independently of what key you press. I've added more information in the [README](https://github.com/jinh0/eyeliner.nvim?tab=readme-ov-file#advanced-configuration) .

Let me know if it works for you! Thanks for the feature suggestion!

(Bonus: I don't know what a solo levelling reference is, but yes, my name is Jinho Yoon.)

**Comment by daUnknownCoder** [comment]
hey bro:
> - You want to map eyeliner's highlights to other keys than f/F/t/T

you didn't tell how to do it?
like the APIs for calling `f`,`t`,`F`,`T`
like can i set it like this:
```lua
vim.keymap.set("n", "x", function() require("eyeliner").highlight({ forward = true }) end)
```
so if i do this, how will `eyeliner` know if its a mapping for `F` or `f` or `t` or `T`?

> (Bonus: I don't know what a solo levelling reference is, but yes, my name is Jinho Yoon.)

Bonus: Solo Leveling is a `Manhwa` (Linguistically, manhwa (漫画) all mean 'comics' in Korean.) - and you somewhat look similar to him: https://solo-leveling.fandom.com/wiki/Yoo_Jinho

![yoo jinho](https://github.com/user-attachments/assets/b8d61834-0c3b-47f2-b74c-b23be4c9eb84)

**Comment by jinh0** [comment]
Hi @daUnknownCoder , `require("eyeliner").highlight` only provides highlights in either direction.

If you want to remap `x` to have `f` functionality, you can do something like this:
```lua
vim.keymap.set(
  {"n", "x", "o"},
  "x",
  function()
    -- Eyeliner only adds highlights, nothing else
    require("eyeliner").highlight({ forward = true })

    -- Get a character from the user
    local char = vim.fn.getcharstr()

    local cnt = vim.v.count1
    while cnt > 0 do
      -- vim's builtin search function
      vim.fn.search(char, "", vim.fn.line("."))
      cnt = cnt - 1
    end
  end
)
```

But reimplementing `f` functionality from scratch seems outside of the scope of eyeliner. You might find `:h search()` helpful.

**Comment by jinh0** [comment]
> so basically F, T, t are empty to be overridden 

Oh okay, how about if I made a configuration option so you can specify which keys you want mapped? So you can map only F, t, T?

```lua
require("eyeliner").setup({
  keys = {"F", "t", "T"}
})
```
and so "f" will be left alone, while eyeliner takes care of "F", "t", and "T".

How does that sound?

**Comment by daUnknownCoder** [comment]
> and so "f" will be left alone, while eyeliner takes care of "F", "t", and "T".

that will be cool, but this is a bad practice you know?
you should do:

1. either this: expose API to each of them like `require("eyeliner").eye("f")` replace with `t` or `T` or `F` for whatever keymaps you choose (only if `require'eyeliner'.setup {default_keymaps = false}` is present)
2. or this: add config option for something like: `require("eyeliner").setup({eye = {"x", "F", "t", "T"}})` accepts 4 strings, keep empty to disable that keymap, order should be f,F,t,T

That will be a good thing

**Comment by jinh0** [comment]
Can you explain why this would be bad practice? I'm taking inspiration from how [quick-scope](https://github.com/unblevable/quick-scope?tab=readme-ov-file#highlight-on-key-press) handles it.

I've added this feature in the latest commit 85e5a5a815651a434f327d0da3c2a33b9aa4f9ec : you can change the highlight_on_key option to be the keys you want eyeliner to work on.
```lua
require("eyeliner").setup({
  highlight_on_key = {"f", "F"}
})
```

Let me know if this works!
