### ISSUE TITLE
Error when uses with mini.notify

### ISSUE THREAD

**Issue by vunhatchuong** [jinh0/eyeliner.nvim#49]
![image](https://github.com/jinh0/eyeliner.nvim/assets/20581504/ae762073-f560-493c-abd8-cd455c13403a)

This error only appears once on the first activation, after that everything is fine.
```lua
return {
        "jinh0/eyeliner.nvim",
        keys = { "f", "F", "t", "T" },
        opts = { highlight_on_key = true, dim = true },
    },
```

**Comment by jinh0** [comment]
This might be due to the same reason as https://github.com/jinh0/eyeliner.nvim/issues/45 . It's been fixed in this latest commit https://github.com/jinh0/eyeliner.nvim/commit/44384110fa4540d4efd3418b96fbeab6472b279b . Let me know if the issue still persists!

**Comment by vunhatchuong** [comment]
Yep fixed, thanks!
