### ISSUE TITLE
Why aren't my custom colors working?

### ISSUE THREAD

**Issue by jonahfang** [jinh0/eyeliner.nvim#56]
![image](https://github.com/user-attachments/assets/bd0300eb-e041-42bd-b897-8239cc44650a)

```
        vim.api.nvim_set_hl(0, 'EyelinerPrimary', { fg='#a05703',bold = true, underline = true })
        vim.api.nvim_set_hl(0, 'EyelinerSecondary', { fg='#a05703', underline = true })
```

The hi query result is:

![image](https://github.com/user-attachments/assets/3bbbeba6-1112-45d4-ad76-223aa2392c07)

**Comment by jinh0** [comment]
I might be wrong, but maybe your Neovim is using cterm colors instead of gui colors? As you can see in your screenshot, bold,underline is present.

Try:
```lua
vim.api.nvim_set_hl(0, 'EyelinerPrimary', { fg='#a05703',bold = true, underline = true, ctermfg=19, ctermbg=230 })
```

**Comment by jonahfang** [comment]
@jinh0 , Thanks for your reply. This code still has no effect:

```
vim.api.nvim_set_hl(0, 'EyelinerPrimary', { fg='#a05703',bold = true, underline = true, ctermfg=19, ctermbg=230 })
```

**Comment by jinh0** [comment]
Hm, this is curious. Can you share your entire eyeliner config? Maybe the plugin is accidentally overriding your highlights...

**Comment by benelan** [comment]
Try creating a `ColorScheme` autocmd before you set your colorscheme, and make all your highlight changes in its callback. I have something like this in my config:

```lua
vim.api.nvim_create_autocmd({ "ColorScheme" }, {
  pattern = "gruvbox-material",
  group = vim.api.nvim_create_augroup("custom_colors", {}),
  callback = function()
    vim.api.nvim_set_hl(
      0,
      "EyelinerPrimary",
      { fg = "#a05703", bold = true, underline = true, ctermfg = 19, ctermbg = 230 }
    )
  end,
})

vim.cmd.colorscheme("gruvbox-material")
```

**Comment by jinh0** [comment]
Good point @benelan , it might be the colorscheme overriding eyeliner's colours. @jonahfang , you can see another example in [this part of the README](https://github.com/jinh0/eyeliner.nvim?tab=readme-ov-file#update-highlights-when-the-colorscheme-is-changed). Closing the issue for now since there hasn't been much activity.
