### ISSUE TITLE
Weird issue on nixos

### ISSUE THREAD

**Issue by damccull** [jinh0/eyeliner.nvim#57]
Hello. I know nixos is probably not the target audience, but I'm getting a weird error from your plugin that didn't used to happen:

```
Error detected while processing /nix/store/qxqcbf1s7882g95qfgia309xqqpkybx1-vimplugin-eyeliner.nvim-2024-08-05/plu
gin/init.lua:
E5113: Error while calling lua chunk: vim/keymap.lua:0: E31: No such mapping
stack traceback:
        [C]: in function 'nvim_buf_del_keymap'
        vim/keymap.lua: in function 'del'
        ...ovimPackages/start/eyeliner.nvim/lua/eyeliner/on-key.lua:63: in function 'remove-keybinds'
        ...NeovimPackages/start/eyeliner.nvim/lua/eyeliner/main.lua:40: in function 'disable'
        ...ovimPackages/start/eyeliner.nvim/lua/eyeliner/config.lua:9: in function 'setup'
        ...kybx1-vimplugin-eyeliner.nvim-2024-08-05/plugin/init.lua:5: in main chunk
```

My guess is something updated in nixos's nvim that makes it incompatible with your plugin, but I'm not familiar with nvims programming API so I don't know what to do here. Can you point me in the right direction?

**Comment by damccull** [comment]
Ok so the only difference I can find so far is that I am updating to 0.10.1 and it's throwing that error.

**Comment by damccull** [comment]
New info. Even if I set back to nvim 0.10.0, it's still having the same issue.

**Comment by mcgilly17** [comment]
Im here with the same issue on NVIM v0.11.0-nightly+9d74dc3 and this version of eyeliner:

  ```
eyeliner-nvim = buildVimPlugin {
    pname = "eyeliner.nvim";
    version = "2024-08-05";
    src = fetchFromGitHub {
      owner = "jinh0";
      repo = "eyeliner.nvim";
      rev = "2ee9e64d4c8133da1131edf0e64641e32dd16396";
      sha256 = "057hkbd5ab1xm2x47b0wvd4qafwinlwhwixqbl6dgdnhbi8my6d0";
    };
    meta.homepage = "https://github.com/jinh0/eyeliner.nvim/";
  };
```

**Comment by mateusauler** [comment]
Potentially related: #51 
I'm having the same issue on the latest unstable nixpkgs.

**Comment by mateusauler** [comment]
> Im here with the same issue on NVIM v0.11.0-nightly+9d74dc3 and this version of eyeliner:
> 
> ```
> eyeliner-nvim = buildVimPlugin {
>   pname = "eyeliner.nvim";
>   version = "2024-08-05";
>   src = fetchFromGitHub {
>     owner = "jinh0";
>     repo = "eyeliner.nvim";
>     rev = "2ee9e64d4c8133da1131edf0e64641e32dd16396";
>     sha256 = "057hkbd5ab1xm2x47b0wvd4qafwinlwhwixqbl6dgdnhbi8my6d0";
>   };
>   meta.homepage = "https://github.com/jinh0/eyeliner.nvim/";
> };
> ```

It's fixed in master.
Here's the version I'm using:

```nix
  eyeliner-nvim = pkgs.vimUtils.buildVimPlugin {
    pname = "eyeliner.nvim";
    version = "2024-08-09";
    src = pkgs.fetchFromGitHub {
      owner = "jinh0";
      repo = "eyeliner.nvim";
      rev = "7385c1a29091b98ddde186ed2d460a1103643148";
      hash = "sha256-PyCcoSC/LeJ/Iuzlm5gd/0lWx8sBS50Vhe7wudgZzqM=";
    };
    meta.homepage = "https://github.com/jinh0/eyeliner.nvim/";
  };
```

**Comment by damccull** [comment]
> > Im here with the same issue on NVIM v0.11.0-nightly+9d74dc3 and this version of eyeliner:
> > ```
> > eyeliner-nvim = buildVimPlugin {
> >   pname = "eyeliner.nvim";
> >   version = "2024-08-05";
> >   src = fetchFromGitHub {
> >     owner = "jinh0";
> >     repo = "eyeliner.nvim";
> >     rev = "2ee9e64d4c8133da1131edf0e64641e32dd16396";
> >     sha256 = "057hkbd5ab1xm2x47b0wvd4qafwinlwhwixqbl6dgdnhbi8my6d0";
> >   };
> >   meta.homepage = "https://github.com/jinh0/eyeliner.nvim/";
> > };
> > ```
> 
> It's fixed in master. Here's the version I'm using:
> 
> ```nix
>   eyeliner-nvim = pkgs.vimUtils.buildVimPlugin {
>     pname = "eyeliner.nvim";
>     version = "2024-08-09";
>     src = pkgs.fetchFromGitHub {
>       owner = "jinh0";
>       repo = "eyeliner.nvim";
>       rev = "7385c1a29091b98ddde186ed2d460a1103643148";
>       hash = "sha256-PyCcoSC/LeJ/Iuzlm5gd/0lWx8sBS50Vhe7wudgZzqM=";
>     };
>     meta.homepage = "https://github.com/jinh0/eyeliner.nvim/";
>   };
> ```

Thanks I'll try this override.

**Comment by damccull** [comment]
Thanks for the heads-up @mateusauler. Pinning to this repo's current master commit fixed it for me. I'll try going back to nixos's main version of it in a few days when it hopefully gets updated.

**Comment by mcgilly17** [comment]
Thanks @mateusauler will check this out right away!

**Comment by mcgilly17** [comment]
Hey @mateusauler just to ask a really stupid question, how do you get the rev and hash of a specific branch or version? I have never worked out how to do it!

**Comment by damccull** [comment]
> Hey @mateusauler just to ask a really stupid question, how do you get the rev and hash of a specific branch or version? I have never worked out how to do it!

I usually open the commit I want and copy it from the URL bar. Or you can use the branch name as well.

**Comment by mcgilly17** [comment]
So simple! thank you very much @damccull

**Comment by mateusauler** [comment]
@mcgilly17, sorry for the late answer. I do it just like @damccull said.
You can also add it as a flake input and grab the results from flake.lock, whatever you prefer.

**Comment by mcgilly17** [comment]
Thanks @mateusauler appreciate you coming back on this!
