### ISSUE TITLE
Conflict with vim-visual-multi

### ISSUE THREAD

**Issue by Sh00Fly** [jinh0/eyeliner.nvim#59]
There seems to be a conflict between eyeliner.nvim and vim-visual-multi plugins.
When eyeliner is enabled it breaks multi-cursor f,F,t,T motions (just one cursor moves).
EyelinerDisable command doesn't fix the issue. Only when eyeliner is completely disabled and not loaded vim-visual-multi works correctly.

**Comment by jinh0** [comment]
Hi @Sh00Fly , not sure how multi-cursor handles the f,F,t,T motions, though I am guessing they remap those keys. What you can do is you can disable eyeliner.nvim from hijacking f,F,t,T mappings with the config
```lua
require'eyeliner'.setup {
  highlight_on_key = true,
  default_keymaps = false
}
```
and you can use eyeliner.nvim's API as explained in [this section of the README](https://github.com/jinh0/eyeliner.nvim?tab=readme-ov-file#advanced-configuration) to make eyeliner.nvim work with multi-cursor.

Let me know how that goes!

**Comment by Sh00Fly** [comment]
Thank you, @jinh0!
I love your plugin, but I love vim-visual-multi too. :)
Now I can keep using them both!
Here is what I ended up doing:
```lua

return {
    "jinh0/eyeliner.nvim",
    config = function()
        require("eyeliner").setup({
            highlight_on_key = true, -- show highlights only after keypress
            dim = false, -- dim all other characters if set to true (recommended!)
            default_keymaps = false,
        })

        vim.keymap.set({ "n", "x", "o" }, "f", function()
            require("eyeliner").highlight({ forward = true })
            return "f"
        end, { expr = true })
        vim.keymap.set({ "n", "x", "o" }, "t", function()
            require("eyeliner").highlight({ forward = true })
            return "t"
        end, { expr = true })
        vim.keymap.set({ "n", "x", "o" }, "F", function()
            require("eyeliner").highlight({ forward = false })
            return "F"
        end, { expr = true })
        vim.keymap.set({ "n", "x", "o" }, "T", function()
            require("eyeliner").highlight({ forward = false })
            return "T"
        end, { expr = true })
    end,
}

```
These keymaps allow eyeliner.nvim do it's job and it doesn't break vim-visual-multi functionality.
Thanks again!
