### ISSUE TITLE
Dimming and highlighting retained after pressing Escape after f/F/t/T

### ISSUE THREAD

**Issue by pksunkara** [jinh0/eyeliner.nvim#60]
Given following config,

```
require('eyeliner').setup({
  highlight_on_key = true,
  dim = true,
})
```

Press `f` and then press `Escape`. You should see the dim and char highlighting. It should be reset.

**Comment by jinh0** [comment]
Should be fixed now thanks to @cosmicbuffalo 's PR. Thanks @cosmicbuffalo for the PR, and thanks @pksunkara  for the issue!
